apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parking-detection-
  namespace: argo
  labels:
    app: parking-detection
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: parkings
      value: |
        [{"name":"test","bbox":[2345990.3,6844431.7,2346242.1,6844603.1]}]
    - name: zoom
      value: "19"
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
  templates:
  - name: main
    dag:
      tasks:
      - name: process-parking
        template: parking-pipeline
        arguments:
          parameters:
          - name: parking
            value: "{{item}}"
          - name: zoom
            value: "{{workflow.parameters.zoom}}"
        withParam: "{{workflow.parameters.parkings}}"
      - name: aggregate-results
        template: aggregator
        dependencies: [process-parking]

  - name: parking-pipeline
    inputs:
      parameters:
      - name: parking
      - name: zoom
    dag:
      tasks:
      - name: fetch-wmts
        template: wmts-fetcher
        arguments:
          parameters:
          - name: parking
            value: "{{inputs.parameters.parking}}"
          - name: zoom
            value: "{{inputs.parameters.zoom}}"
      - name: detect-vehicles
        template: yolo-inference
        dependencies: [fetch-wmts]
        arguments:
          parameters:
          - name: parking-name
            value: "{{=jsonpath(inputs.parameters.parking, '$.name')}}"
      - name: convert-geo
        template: geo-converter
        dependencies: [detect-vehicles]
        arguments:
          parameters:
          - name: parking-name
            value: "{{=jsonpath(inputs.parameters.parking, '$.name')}}"

  - name: wmts-fetcher
    inputs:
      parameters:
      - name: parking
      - name: zoom
    container:
      image: ghcr.io/mathewnwsh/argo-workflows-use-case/wmts-fetcher:latest
      env:
      - name: PARKING_JSON
        value: "{{inputs.parameters.parking}}"
      - name: ZOOM
        value: "{{inputs.parameters.zoom}}"
      - name: OUTPUT_DIR
        value: /data/output
      volumeMounts:
      - name: workdir
        mountPath: /data
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "500m"

  - name: yolo-inference
    inputs:
      parameters:
      - name: parking-name
    container:
      image: ghcr.io/mathewnwsh/argo-workflows-use-case/yolo-inference:latest
      env:
      - name: TILES_DIR
        value: "/data/output/{{inputs.parameters.parking-name}}"
      - name: MODEL_PATH
        value: /model/yolo26m-obb.pt
      - name: OUTPUT_DIR
        value: /data/output
      volumeMounts:
      - name: workdir
        mountPath: /data
      resources:
        requests:
          memory: "2Gi"
          cpu: "1000m"
        limits:
          memory: "8Gi"
          cpu: "4000m"

  - name: geo-converter
    inputs:
      parameters:
      - name: parking-name
    container:
      image: ghcr.io/mathewnwsh/argo-workflows-use-case/geo-converter:latest
      env:
      - name: TILES_DIR
        value: "/data/output/{{inputs.parameters.parking-name}}"
      - name: DETECTIONS_DIR
        value: /data/output
      - name: OUTPUT_DIR
        value: /data/output
      volumeMounts:
      - name: workdir
        mountPath: /data
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "200m"

  - name: aggregator
    container:
      image: ghcr.io/mathewnwsh/argo-workflows-use-case/aggregator:latest
      env:
      - name: INPUT_DIR
        value: /data/output
      - name: OUTPUT_DIR
        value: /data/final
      volumeMounts:
      - name: workdir
        mountPath: /data
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "200m"
    outputs:
      artifacts:
      - name: all-parkings-geojson
        path: /data/final/all_parkings.geojson
        archive:
          none: {}
        s3:
          endpoint: s3.waw3-2.cloudferro.com
          bucket: outputing
          region: default
          key: parkings/{{workflow.name}}/all_parkings.geojson
          accessKeySecret:
            name: cloudferro-s3-credentials
            key: accessKey
          secretKeySecret:
            name: cloudferro-s3-credentials
            key: secretKey
      - name: stats-csv
        path: /data/final/stats.csv
        archive:
          none: {}
        s3:
          endpoint: s3.waw3-2.cloudferro.com
          bucket: outputing
          region: default
          key: parkings/{{workflow.name}}/stats.csv
          accessKeySecret:
            name: cloudferro-s3-credentials
            key: accessKey
          secretKeySecret:
            name: cloudferro-s3-credentials
            key: secretKey